const PERMISSIONS = {
  MANAGE_BRANCHES: 'manage_branches',
  MANAGE_ETIMS: 'manage_etims'
};

const ORDER_STATUSES = {
  PENDING: 'pending',
  APPROVED: 'approved',
  PREPARING: 'preparing',
  OUT_FOR_DELIVERY: 'out_for_delivery',
  COMPLETED: 'completed',
  REJECTED: 'rejected',
  CANCELLED: 'cancelled'
};

const ROLES = {
  GUEST: 'guest',
  CUSTOMER: 'customer',
  DRIVER: 'driver',
  STAFF: 'staff',
  SUPERVISOR: 'supervisor',
  ADMIN: 'admin',
  SUPERADMIN: 'superadmin'
};

const STOCK_CHANGE_TYPES = {
  DELIVERY: 'delivery',
  ORDER_RESERVATION: 'order_reservation',
  ORDER_DEDUCTION: 'order_deduction',
  ORDER_RELEASE: 'order_release',
  MANUAL_ADJUSTMENT: 'manual_adjustment',
  RETURN: 'return'
};

const STOCK_RESERVATION_STATUSES = {
  NONE: 'none',
  HELD: 'held',
  RELEASED: 'released',
  CONSUMED: 'consumed'
};

const PAYMENT_METHODS = {
  MPESA: 'mpesa',
  PICKUP: 'pickup',
  DELIVERY: 'delivery'
};

const PAYMENT_STATUSES = {
  UNPAID: 'unpaid',
  PENDING: 'pending',
  PAID: 'paid',
  FAILED: 'failed',
  REFUNDED: 'refunded'
};

const DELIVERY_METHODS = {
  PICKUP: 'pickup',
  DELIVERY: 'delivery'
};

const LOG_ACTIONS = {
  // Auth
  ADMIN_LOGIN: 'ADMIN_LOGIN',
  ADMIN_LOGOUT: 'ADMIN_LOGOUT',
  ADMIN_BRANCH_SELECTED: 'ADMIN_BRANCH_SELECTED',
  CUSTOMER_LOGIN: 'CUSTOMER_LOGIN',
  CUSTOMER_LOGOUT: 'CUSTOMER_LOGOUT',
  CUSTOMER_REGISTERED: 'CUSTOMER_REGISTERED',
  FAILED_LOGIN: 'FAILED_LOGIN',
  TOKEN_REFRESHED: 'TOKEN_REFRESHED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED: 'PASSWORD_RESET_COMPLETED',
  // System backups
  SYSTEM_BACKUP_CREATED: 'SYSTEM_BACKUP_CREATED',
  SYSTEM_BACKUP_RESTORED: 'SYSTEM_BACKUP_RESTORED',
  SYSTEM_BACKUP_DELETED: 'SYSTEM_BACKUP_DELETED',
  // Orders
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_APPROVED: 'ORDER_APPROVED',
  ORDER_REJECTED: 'ORDER_REJECTED',
  ORDER_STATUS_CHANGED: 'ORDER_STATUS_CHANGED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  // Products
  PRODUCT_ADDED: 'PRODUCT_ADDED',
  PRODUCT_EDITED: 'PRODUCT_EDITED',
  PRODUCT_DELETED: 'PRODUCT_DELETED',
  PRODUCT_ACTIVATED: 'PRODUCT_ACTIVATED',
  PRODUCT_DEACTIVATED: 'PRODUCT_DEACTIVATED',
  // Stock
  STOCK_DELIVERY_ADDED: 'STOCK_DELIVERY_ADDED',
  STOCK_MANUALLY_ADJUSTED: 'STOCK_MANUALLY_ADJUSTED',
  STOCK_DEDUCTED_BY_ORDER: 'STOCK_DEDUCTED_BY_ORDER',
  // Payments
  PAYMENT_CONFIRMED: 'PAYMENT_CONFIRMED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_MANUALLY_CONFIRMED: 'PAYMENT_MANUALLY_CONFIRMED',
  PAYMENT_REFUNDED: 'PAYMENT_REFUNDED',
  // Accounts
  ADMIN_CREATED: 'ADMIN_CREATED',
  ADMIN_ROLE_CHANGED: 'ADMIN_ROLE_CHANGED',
  ADMIN_ACCOUNT_LOCKED: 'ADMIN_ACCOUNT_LOCKED',
  ADMIN_ACCOUNT_UNLOCKED: 'ADMIN_ACCOUNT_UNLOCKED',
  ADMIN_PASSWORD_RESET: 'ADMIN_PASSWORD_RESET',
  CUSTOMER_ACCOUNT_LOCKED: 'CUSTOMER_ACCOUNT_LOCKED',
  CUSTOMER_ACCOUNT_UNLOCKED: 'CUSTOMER_ACCOUNT_UNLOCKED',
  // Drivers
  DRIVER_CREATED: 'DRIVER_CREATED',
  DRIVER_ACCOUNT_LOCKED: 'DRIVER_ACCOUNT_LOCKED',
  DRIVER_ACCOUNT_UNLOCKED: 'DRIVER_ACCOUNT_UNLOCKED',
  DRIVER_PASSWORD_RESET: 'DRIVER_PASSWORD_RESET',
  DRIVER_ASSIGNED_TO_ORDER: 'DRIVER_ASSIGNED_TO_ORDER',
  DRIVER_AVAILABILITY_CHANGED: 'DRIVER_AVAILABILITY_CHANGED',
  // Stock Intake
  INTAKE_LOGGED:    'INTAKE_LOGGED',
  INTAKE_PROCESSED: 'INTAKE_PROCESSED',
  INTAKE_DELETED:   'INTAKE_DELETED',
  // eTIMS
  ETIMS_INVOICE_SUBMITTED: 'ETIMS_INVOICE_SUBMITTED',
  ETIMS_INVOICE_FAILED:    'ETIMS_INVOICE_FAILED',
  // Settings / System
  SETTINGS_UPDATED: 'SETTINGS_UPDATED',
  PLATFORM_LOCKED: 'PLATFORM_LOCKED',
  PLATFORM_UNLOCKED: 'PLATFORM_UNLOCKED',
  // Permissions
  USER_PERMISSIONS_UPDATED: 'USER_PERMISSIONS_UPDATED',
  // Marketing
  SMS_BROADCAST_SENT: 'SMS_BROADCAST_SENT',
};

// Valid order status transitions - only these are allowed
// CANCELLED is reachable from every non-terminal stage because admins/staff can
// cancel an order at any point (order.service.js's updateStatus, staff+ only) —
// customers are independently restricted to pending-only cancellation via their
// own cancel() function, which never consults this table.
const ORDER_STATUS_TRANSITIONS = {
  [ORDER_STATUSES.PENDING]: [ORDER_STATUSES.APPROVED, ORDER_STATUSES.REJECTED, ORDER_STATUSES.CANCELLED],
  [ORDER_STATUSES.APPROVED]: [ORDER_STATUSES.PREPARING, ORDER_STATUSES.CANCELLED],
  [ORDER_STATUSES.PREPARING]: [ORDER_STATUSES.OUT_FOR_DELIVERY, ORDER_STATUSES.CANCELLED],
  [ORDER_STATUSES.OUT_FOR_DELIVERY]: [ORDER_STATUSES.COMPLETED, ORDER_STATUSES.CANCELLED],
  [ORDER_STATUSES.COMPLETED]: [],
  [ORDER_STATUSES.REJECTED]: [],
  [ORDER_STATUSES.CANCELLED]: []
};

const PACKAGING_SIZES = ['45kg', '50kg', '90kg', '100kg', 'Bulk'];

const AUTH_LIMITS = {
  MAX_FAILED_LOGINS: 5,
  ALERT_THRESHOLD: 3,
  BCRYPT_WORK_FACTOR: 12,
  PRE_AUTH_TOKEN_EXPIRY: '5m',
  REFRESH_COOKIE_MAX_AGE_MS: 7 * 24 * 60 * 60 * 1000,
  OTP_EXPIRY_MINUTES: 10,
  OTP_MAX_ATTEMPTS: 5
};

const MPESA_RECEIPT_REGEX = /^[A-Z0-9]{10}$/;

const DB_RETRY = {
  MAX_RETRIES: 5,
  BASE_DELAY_MS: 1000
};

const RATE_LIMITS = {
  WINDOW_MS: 60 * 1000,
  PUBLIC_MAX: 100,
  AUTH_MAX: 10,
  ADMIN_MAX: 300,
  CALLBACK_MAX: 30,
  STK_MAX: 5,
  TRACK_MAX: 20
};

const REQUEST_TIMING = {
  DEFAULT_SLOW_THRESHOLD_MS: 1200
};

const UPLOAD_LIMITS = {
  IMAGE_MAX_FILE_SIZE_BYTES: 5 * 1024 * 1024,
  PRODUCT_MAX_IMAGES: 5
};

module.exports = {
  PERMISSIONS,
  ORDER_STATUSES,
  ROLES,
  STOCK_CHANGE_TYPES,
  STOCK_RESERVATION_STATUSES,
  PAYMENT_METHODS,
  PAYMENT_STATUSES,
  DELIVERY_METHODS,
  LOG_ACTIONS,
  ORDER_STATUS_TRANSITIONS,
  PACKAGING_SIZES,
  AUTH_LIMITS,
  DB_RETRY,
  RATE_LIMITS,
  REQUEST_TIMING,
  UPLOAD_LIMITS,
  MPESA_RECEIPT_REGEX
};
