const ORDER_STATUSES = {
  PENDING: 'pending',
  APPROVED: 'approved',
  PREPARING: 'preparing',
  OUT_FOR_DELIVERY: 'out_for_delivery',
  COMPLETED: 'completed',
  REJECTED: 'rejected',
  CANCELLED: 'cancelled'
};

const ROLES = {
  GUEST: 'guest',
  CUSTOMER: 'customer',
  STAFF: 'staff',
  SUPERVISOR: 'supervisor',
  ADMIN: 'admin',
  SUPERADMIN: 'superadmin'
};

const STOCK_CHANGE_TYPES = {
  DELIVERY: 'delivery',
  ORDER_RESERVATION: 'order_reservation',
  ORDER_DEDUCTION: 'order_deduction',
  ORDER_RELEASE: 'order_release',
  MANUAL_ADJUSTMENT: 'manual_adjustment',
  RETURN: 'return'
};

const STOCK_RESERVATION_STATUSES = {
  NONE: 'none',
  HELD: 'held',
  RELEASED: 'released',
  CONSUMED: 'consumed'
};

const PAYMENT_METHODS = {
  MPESA: 'mpesa',
  PICKUP: 'pickup',
  DELIVERY: 'delivery'
};

const PAYMENT_STATUSES = {
  PENDING: 'pending',
  PAID: 'paid',
  FAILED: 'failed',
  REFUNDED: 'refunded'
};

const DELIVERY_METHODS = {
  PICKUP: 'pickup',
  DELIVERY: 'delivery'
};

const LOG_ACTIONS = {
  // Auth
  ADMIN_LOGIN: 'ADMIN_LOGIN',
  ADMIN_LOGOUT: 'ADMIN_LOGOUT',
  CUSTOMER_LOGIN: 'CUSTOMER_LOGIN',
  FAILED_LOGIN: 'FAILED_LOGIN',
  // System backups
  SYSTEM_BACKUP_CREATED: 'SYSTEM_BACKUP_CREATED',
  SYSTEM_BACKUP_RESTORED: 'SYSTEM_BACKUP_RESTORED',
  SYSTEM_BACKUP_DELETED: 'SYSTEM_BACKUP_DELETED',
  // Orders
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_APPROVED: 'ORDER_APPROVED',
  ORDER_REJECTED: 'ORDER_REJECTED',
  ORDER_STATUS_CHANGED: 'ORDER_STATUS_CHANGED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  // Products
  PRODUCT_ADDED: 'PRODUCT_ADDED',
  PRODUCT_EDITED: 'PRODUCT_EDITED',
  PRODUCT_DELETED: 'PRODUCT_DELETED',
  PRODUCT_ACTIVATED: 'PRODUCT_ACTIVATED',
  PRODUCT_DEACTIVATED: 'PRODUCT_DEACTIVATED',
  // Stock
  STOCK_DELIVERY_ADDED: 'STOCK_DELIVERY_ADDED',
  STOCK_MANUALLY_ADJUSTED: 'STOCK_MANUALLY_ADJUSTED',
  STOCK_DEDUCTED_BY_ORDER: 'STOCK_DEDUCTED_BY_ORDER',
  // Payments
  PAYMENT_CONFIRMED: 'PAYMENT_CONFIRMED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_MANUALLY_CONFIRMED: 'PAYMENT_MANUALLY_CONFIRMED',
  PAYMENT_REFUNDED: 'PAYMENT_REFUNDED',
  // Accounts
  ADMIN_CREATED: 'ADMIN_CREATED',
  ADMIN_ROLE_CHANGED: 'ADMIN_ROLE_CHANGED',
  ADMIN_ACCOUNT_LOCKED: 'ADMIN_ACCOUNT_LOCKED',
  ADMIN_ACCOUNT_UNLOCKED: 'ADMIN_ACCOUNT_UNLOCKED',
  ADMIN_PASSWORD_RESET: 'ADMIN_PASSWORD_RESET',
  CUSTOMER_ACCOUNT_LOCKED: 'CUSTOMER_ACCOUNT_LOCKED',
  CUSTOMER_ACCOUNT_UNLOCKED: 'CUSTOMER_ACCOUNT_UNLOCKED',
  // Settings / System
  SETTINGS_UPDATED: 'SETTINGS_UPDATED',
  PLATFORM_LOCKED: 'PLATFORM_LOCKED',
  PLATFORM_UNLOCKED: 'PLATFORM_UNLOCKED',
};

// Valid order status transitions - only these are allowed
const ORDER_STATUS_TRANSITIONS = {
  [ORDER_STATUSES.PENDING]: [ORDER_STATUSES.APPROVED, ORDER_STATUSES.REJECTED, ORDER_STATUSES.CANCELLED],
  [ORDER_STATUSES.APPROVED]: [ORDER_STATUSES.PREPARING, ORDER_STATUSES.CANCELLED],
  [ORDER_STATUSES.PREPARING]: [ORDER_STATUSES.OUT_FOR_DELIVERY],
  [ORDER_STATUSES.OUT_FOR_DELIVERY]: [ORDER_STATUSES.COMPLETED],
  [ORDER_STATUSES.COMPLETED]: [],
  [ORDER_STATUSES.REJECTED]: [],
  [ORDER_STATUSES.CANCELLED]: []
};

const PACKAGING_SIZES = ['45kg', '50kg', '90kg', '100kg', 'Bulk'];

module.exports = {
  ORDER_STATUSES,
  ROLES,
  STOCK_CHANGE_TYPES,
  STOCK_RESERVATION_STATUSES,
  PAYMENT_METHODS,
  PAYMENT_STATUSES,
  DELIVERY_METHODS,
  LOG_ACTIONS,
  ORDER_STATUS_TRANSITIONS,
  PACKAGING_SIZES
};
